### ISSUE TITLE
Order of repeats

### ISSUE THREAD

**Issue by jnyvng** [ODonoghueLab/versus#48]
If possible, the order of when a repeat image pair is shown, should not be right after the first time it is shown. It should be interleaved in between all the other image pairs as to prevent the user to notice any repeats. This has been mentioned in Julian's Aesthetics paper: 

> Interleaved in this process, at regular intervals (determined by a binomial distribution), two images, which had previously been shown were shown again, and the response was recorded.

**Comment by boscoh** [comment]
Could you clarify what happens if one chooses to repeat 100% of the seen pairings? 

As I far is I understand, it's impossible to interleave the repeats. To interleave all pairings, you would have to show effectively non-repeat / repeat / no-repeat ... etc. Otherwise, you would end up with a bunch of repeats after all the non-repeats have been shown.

**Comment by jnyvng** [comment]
The answer to this is the same as in the other issue. As the confusion has already been addressed in the other issue, I will close this.
